// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// AddDevice implements addDevice operation.
//
// Add a device. Please note that the new device is assigned to the owner currently logged in.
//
// POST /api/devices
func (UnimplementedHandler) AddDevice(ctx context.Context, req *AddDeviceReq) (r AddDeviceRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetDeviceStatus implements getDeviceStatus operation.
//
// Get device status by ID.
//
// GET /api/devices/{deviceId}/status
func (UnimplementedHandler) GetDeviceStatus(ctx context.Context, params GetDeviceStatusParams) (r GetDeviceStatusRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetDevices implements getDevices operation.
//
// Get list of devices that match the provided filters.
//
// GET /api/devices
func (UnimplementedHandler) GetDevices(ctx context.Context, params GetDevicesParams) (r GetDevicesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetHealth implements getHealth operation.
//
// Check if server is up.
//
// GET /health
func (UnimplementedHandler) GetHealth(ctx context.Context) error {
	return ht.ErrNotImplemented
}

// Login implements login operation.
//
// Log into an account. This endpoint return a token to use in header bearer for authentication.
//
// POST /api/users/login
func (UnimplementedHandler) Login(ctx context.Context, req *LoginReq) (r LoginRes, _ error) {
	return r, ht.ErrNotImplemented
}

// Register implements register operation.
//
// Register a user.
//
// POST /api/users/register
func (UnimplementedHandler) Register(ctx context.Context, req *RegisterReq) (r RegisterRes, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *DefaultStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *DefaultStatusCode) {
	r = new(DefaultStatusCode)
	return r
}
