// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	AddDeviceOperation       OperationName = "AddDevice"
	ChangePasswordOperation  OperationName = "ChangePassword"
	GetDeviceStatusOperation OperationName = "GetDeviceStatus"
	GetDevicesOperation      OperationName = "GetDevices"
	GetHealthOperation       OperationName = "GetHealth"
	LoginOperation           OperationName = "Login"
	OrderDeviceOperation     OperationName = "OrderDevice"
	RegisterOperation        OperationName = "Register"
)
