// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// AddDevice implements addDevice operation.
//
// Register a device. The device is assigned to the owner that's currently logged in.
//
// POST /api/devices
func (UnimplementedHandler) AddDevice(ctx context.Context, req *AddDeviceReq) (r AddDeviceRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ChangePassword implements changePassword operation.
//
// Change current logged in user's password.
//
// POST /api/users/changePassword
func (UnimplementedHandler) ChangePassword(ctx context.Context, req *ChangePasswordReq) (r ChangePasswordRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetDeviceStatus implements getDeviceStatus operation.
//
// Get device status by ID.
//
// GET /api/devices/{deviceId}/status
func (UnimplementedHandler) GetDeviceStatus(ctx context.Context, params GetDeviceStatusParams) (r GetDeviceStatusRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetDevices implements getDevices operation.
//
// Get list of devices that match the provided filters. If an auth token is provided, it returns only
// the devices owned by the authenticated user.
//
// GET /api/devices
func (UnimplementedHandler) GetDevices(ctx context.Context, params GetDevicesParams) (r GetDevicesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetHealth implements getHealth operation.
//
// Check if server is up.
//
// GET /health
func (UnimplementedHandler) GetHealth(ctx context.Context) error {
	return ht.ErrNotImplemented
}

// GetOrderById implements getOrderById operation.
//
// Get a user's order.
//
// GET /api/orders/{orderId}
func (UnimplementedHandler) GetOrderById(ctx context.Context, params GetOrderByIdParams) (r GetOrderByIdRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetOrders implements getOrders operation.
//
// Get a list of user's orders.
//
// GET /api/orders
func (UnimplementedHandler) GetOrders(ctx context.Context, params GetOrdersParams) (r GetOrdersRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetReviewsByDeviceId implements getReviewsByDeviceId operation.
//
// Returns a list of all reviews associated with a specific device.
//
// GET /api/reviews/device/{deviceId}
func (UnimplementedHandler) GetReviewsByDeviceId(ctx context.Context, params GetReviewsByDeviceIdParams) (r GetReviewsByDeviceIdRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetReviewsByUsername implements getReviewsByUsername operation.
//
// Returns a list of all reviews authored by or associated with a specific user.
//
// GET /api/reviews/user/{username}
func (UnimplementedHandler) GetReviewsByUsername(ctx context.Context, params GetReviewsByUsernameParams) (r GetReviewsByUsernameRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetUserRating implements getUserRating operation.
//
// Returns the calculated average rating and the total count of reviews for a specific user.
//
// GET /api/reviews/userRating/{username}
func (UnimplementedHandler) GetUserRating(ctx context.Context, params GetUserRatingParams) (r GetUserRatingRes, _ error) {
	return r, ht.ErrNotImplemented
}

// Login implements login operation.
//
// Log into an account. Returns a token to use in the Authorization header as a Bearer token for
// authentication.
//
// POST /api/users/login
func (UnimplementedHandler) Login(ctx context.Context, req *LoginReq) (r LoginRes, _ error) {
	return r, ht.ErrNotImplemented
}

// OrderDevice implements orderDevice operation.
//
// Initialize a device rental.
//
// POST /api/orders
func (UnimplementedHandler) OrderDevice(ctx context.Context, req *OrderDeviceReq) (r OrderDeviceRes, _ error) {
	return r, ht.ErrNotImplemented
}

// Refresh implements refresh operation.
//
// Refresh the Bearer token for logged in user.
//
// GET /api/users/refresh
func (UnimplementedHandler) Refresh(ctx context.Context) (r RefreshRes, _ error) {
	return r, ht.ErrNotImplemented
}

// Register implements register operation.
//
// Register a user.
//
// POST /api/users/register
func (UnimplementedHandler) Register(ctx context.Context, req *RegisterReq) (r RegisterRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ReviewOrderById implements reviewOrderById operation.
//
// Creates a one-time review for a specific order after the session has been completed.
//
// POST /api/reviews/reviewOrder/{orderId}
func (UnimplementedHandler) ReviewOrderById(ctx context.Context, req *ReviewOrderByIdReq, params ReviewOrderByIdParams) (r ReviewOrderByIdRes, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *DefaultStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *DefaultStatusCode) {
	r = new(DefaultStatusCode)
	return r
}
