// Code generated by ogen, DO NOT EDIT.
package api

type AddDeviceRes interface {
	addDeviceRes()
}

type ChangePasswordRes interface {
	changePasswordRes()
}

type GetDeviceStatusRes interface {
	getDeviceStatusRes()
}

type GetDevicesRes interface {
	getDevicesRes()
}

type GetOrderByIdRes interface {
	getOrderByIdRes()
}

type GetOrdersRes interface {
	getOrdersRes()
}

type LoginRes interface {
	loginRes()
}

type OrderDeviceRes interface {
	orderDeviceRes()
}

type RegisterRes interface {
	registerRes()
}
