// Code generated by ogen, DO NOT EDIT.
package api

type AddDeviceRes interface {
	addDeviceRes()
}

type ChangePasswordRes interface {
	changePasswordRes()
}

type GetDeviceStatusRes interface {
	getDeviceStatusRes()
}

type GetDevicesRes interface {
	getDevicesRes()
}

type GetOrderByIdRes interface {
	getOrderByIdRes()
}

type GetOrdersRes interface {
	getOrdersRes()
}

type GetReviewsByDeviceIdRes interface {
	getReviewsByDeviceIdRes()
}

type GetReviewsByUsernameRes interface {
	getReviewsByUsernameRes()
}

type GetUserRatingRes interface {
	getUserRatingRes()
}

type LoginRes interface {
	loginRes()
}

type OrderDeviceRes interface {
	orderDeviceRes()
}

type RefreshRes interface {
	refreshRes()
}

type RegisterRes interface {
	registerRes()
}

type ReviewOrderByIdRes interface {
	reviewOrderByIdRes()
}
