// Code generated by ogen, DO NOT EDIT.
package api

type AddDeviceRes interface {
	addDeviceRes()
}

type GetDeviceStatusRes interface {
	getDeviceStatusRes()
}

type GetDevicesRes interface {
	getDevicesRes()
}
