// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// GetDeviceStatus implements getDeviceStatus operation.
//
// Get device status by ID.
//
// GET /api/devices/{deviceId}/status
func (UnimplementedHandler) GetDeviceStatus(ctx context.Context, params GetDeviceStatusParams) (r GetDeviceStatusRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetDevices implements getDevices operation.
//
// Get list of devices that match the provided filters.
//
// GET /api/devices
func (UnimplementedHandler) GetDevices(ctx context.Context, params GetDevicesParams) (r GetDevicesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetHealth implements getHealth operation.
//
// Check if server is up.
//
// GET /health
func (UnimplementedHandler) GetHealth(ctx context.Context) (r *GetHealthOKHeaders, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *ErrorStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *ErrorStatusCode) {
	r = new(ErrorStatusCode)
	return r
}
