// Code generated by ogen, DO NOT EDIT.

package api

import (
	"fmt"
	"time"

	"github.com/go-faster/errors"
)

func (s *DefaultStatusCode) Error() string {
	return fmt.Sprintf("code %d: %+v", s.StatusCode, s.Response)
}

type AddDeviceBadRequest struct {
	ErrorMessage string `json:"errorMessage"`
}

// GetErrorMessage returns the value of ErrorMessage.
func (s *AddDeviceBadRequest) GetErrorMessage() string {
	return s.ErrorMessage
}

// SetErrorMessage sets the value of ErrorMessage.
func (s *AddDeviceBadRequest) SetErrorMessage(val string) {
	s.ErrorMessage = val
}

func (*AddDeviceBadRequest) addDeviceRes() {}

type AddDeviceCreated struct {
	DeviceId      string    `json:"deviceId"`
	OwnerUsername string    `json:"ownerUsername"`
	State         State     `json:"state"`
	CreatedAt     time.Time `json:"createdAt"`
}

// GetDeviceId returns the value of DeviceId.
func (s *AddDeviceCreated) GetDeviceId() string {
	return s.DeviceId
}

// GetOwnerUsername returns the value of OwnerUsername.
func (s *AddDeviceCreated) GetOwnerUsername() string {
	return s.OwnerUsername
}

// GetState returns the value of State.
func (s *AddDeviceCreated) GetState() State {
	return s.State
}

// GetCreatedAt returns the value of CreatedAt.
func (s *AddDeviceCreated) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// SetDeviceId sets the value of DeviceId.
func (s *AddDeviceCreated) SetDeviceId(val string) {
	s.DeviceId = val
}

// SetOwnerUsername sets the value of OwnerUsername.
func (s *AddDeviceCreated) SetOwnerUsername(val string) {
	s.OwnerUsername = val
}

// SetState sets the value of State.
func (s *AddDeviceCreated) SetState(val State) {
	s.State = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *AddDeviceCreated) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

func (*AddDeviceCreated) addDeviceRes() {}

type AddDeviceReq struct {
	Name      string `json:"name"`
	GpuModel  string `json:"gpuModel"`
	VramMb    int    `json:"vramMb"`
	CudaCores int    `json:"cudaCores"`
	// Price per active usage hour in USD cents, for example a value of `45` means `0.45 USD/h`.
	PricePerHourUsdCents int `json:"pricePerHourUsdCents"`
	// Driver version expressed as the major version followed by a period and a minor version.
	DriverVersion string `json:"driverVersion"`
}

// GetName returns the value of Name.
func (s *AddDeviceReq) GetName() string {
	return s.Name
}

// GetGpuModel returns the value of GpuModel.
func (s *AddDeviceReq) GetGpuModel() string {
	return s.GpuModel
}

// GetVramMb returns the value of VramMb.
func (s *AddDeviceReq) GetVramMb() int {
	return s.VramMb
}

// GetCudaCores returns the value of CudaCores.
func (s *AddDeviceReq) GetCudaCores() int {
	return s.CudaCores
}

// GetPricePerHourUsdCents returns the value of PricePerHourUsdCents.
func (s *AddDeviceReq) GetPricePerHourUsdCents() int {
	return s.PricePerHourUsdCents
}

// GetDriverVersion returns the value of DriverVersion.
func (s *AddDeviceReq) GetDriverVersion() string {
	return s.DriverVersion
}

// SetName sets the value of Name.
func (s *AddDeviceReq) SetName(val string) {
	s.Name = val
}

// SetGpuModel sets the value of GpuModel.
func (s *AddDeviceReq) SetGpuModel(val string) {
	s.GpuModel = val
}

// SetVramMb sets the value of VramMb.
func (s *AddDeviceReq) SetVramMb(val int) {
	s.VramMb = val
}

// SetCudaCores sets the value of CudaCores.
func (s *AddDeviceReq) SetCudaCores(val int) {
	s.CudaCores = val
}

// SetPricePerHourUsdCents sets the value of PricePerHourUsdCents.
func (s *AddDeviceReq) SetPricePerHourUsdCents(val int) {
	s.PricePerHourUsdCents = val
}

// SetDriverVersion sets the value of DriverVersion.
func (s *AddDeviceReq) SetDriverVersion(val string) {
	s.DriverVersion = val
}

// AddDeviceUnauthorized is response for AddDevice operation.
type AddDeviceUnauthorized struct{}

func (*AddDeviceUnauthorized) addDeviceRes() {}

// Ref: #
type AuthToken struct {
	Token string `json:"token"`
}

// GetToken returns the value of Token.
func (s *AuthToken) GetToken() string {
	return s.Token
}

// SetToken sets the value of Token.
func (s *AuthToken) SetToken(val string) {
	s.Token = val
}

func (*AuthToken) loginRes()    {}
func (*AuthToken) refreshRes()  {}
func (*AuthToken) registerRes() {}

type BearerAuth struct {
	Token string
	Roles []string
}

// GetToken returns the value of Token.
func (s *BearerAuth) GetToken() string {
	return s.Token
}

// GetRoles returns the value of Roles.
func (s *BearerAuth) GetRoles() []string {
	return s.Roles
}

// SetToken sets the value of Token.
func (s *BearerAuth) SetToken(val string) {
	s.Token = val
}

// SetRoles sets the value of Roles.
func (s *BearerAuth) SetRoles(val []string) {
	s.Roles = val
}

// ChangePasswordBadRequest is response for ChangePassword operation.
type ChangePasswordBadRequest struct{}

func (*ChangePasswordBadRequest) changePasswordRes() {}

// ChangePasswordOK is response for ChangePassword operation.
type ChangePasswordOK struct{}

func (*ChangePasswordOK) changePasswordRes() {}

type ChangePasswordReq struct {
	OldPassword string `json:"oldPassword"`
	NewPassword string `json:"newPassword"`
}

// GetOldPassword returns the value of OldPassword.
func (s *ChangePasswordReq) GetOldPassword() string {
	return s.OldPassword
}

// GetNewPassword returns the value of NewPassword.
func (s *ChangePasswordReq) GetNewPassword() string {
	return s.NewPassword
}

// SetOldPassword sets the value of OldPassword.
func (s *ChangePasswordReq) SetOldPassword(val string) {
	s.OldPassword = val
}

// SetNewPassword sets the value of NewPassword.
func (s *ChangePasswordReq) SetNewPassword(val string) {
	s.NewPassword = val
}

// ChangePasswordUnauthorized is response for ChangePassword operation.
type ChangePasswordUnauthorized struct{}

func (*ChangePasswordUnauthorized) changePasswordRes() {}

// Ref: #
type ConnectionDetails struct {
	Host     string `json:"host"`
	Port     string `json:"port"`
	Protocol string `json:"protocol"`
}

// GetHost returns the value of Host.
func (s *ConnectionDetails) GetHost() string {
	return s.Host
}

// GetPort returns the value of Port.
func (s *ConnectionDetails) GetPort() string {
	return s.Port
}

// GetProtocol returns the value of Protocol.
func (s *ConnectionDetails) GetProtocol() string {
	return s.Protocol
}

// SetHost sets the value of Host.
func (s *ConnectionDetails) SetHost(val string) {
	s.Host = val
}

// SetPort sets the value of Port.
func (s *ConnectionDetails) SetPort(val string) {
	s.Port = val
}

// SetProtocol sets the value of Protocol.
func (s *ConnectionDetails) SetProtocol(val string) {
	s.Protocol = val
}

// DefaultStatusCode wraps Error with StatusCode.
type DefaultStatusCode struct {
	StatusCode int
	Response   Error
}

// GetStatusCode returns the value of StatusCode.
func (s *DefaultStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *DefaultStatusCode) GetResponse() Error {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *DefaultStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *DefaultStatusCode) SetResponse(val Error) {
	s.Response = val
}

// Ref: #
type Device struct {
	DeviceId  string `json:"deviceId"`
	Name      string `json:"name"`
	GpuModel  string `json:"gpuModel"`
	VramMb    int    `json:"vramMb"`
	CudaCores int    `json:"cudaCores"`
	// Price per active usage hour in USD cents, for example a value of `45` means `0.45 USD/h`.
	PricePerHourUsdCents int `json:"pricePerHourUsdCents"`
	// Driver version expressed as the major version followed by a period and a minor version.
	DriverVersion string `json:"driverVersion"`
	State         State  `json:"state"`
}

// GetDeviceId returns the value of DeviceId.
func (s *Device) GetDeviceId() string {
	return s.DeviceId
}

// GetName returns the value of Name.
func (s *Device) GetName() string {
	return s.Name
}

// GetGpuModel returns the value of GpuModel.
func (s *Device) GetGpuModel() string {
	return s.GpuModel
}

// GetVramMb returns the value of VramMb.
func (s *Device) GetVramMb() int {
	return s.VramMb
}

// GetCudaCores returns the value of CudaCores.
func (s *Device) GetCudaCores() int {
	return s.CudaCores
}

// GetPricePerHourUsdCents returns the value of PricePerHourUsdCents.
func (s *Device) GetPricePerHourUsdCents() int {
	return s.PricePerHourUsdCents
}

// GetDriverVersion returns the value of DriverVersion.
func (s *Device) GetDriverVersion() string {
	return s.DriverVersion
}

// GetState returns the value of State.
func (s *Device) GetState() State {
	return s.State
}

// SetDeviceId sets the value of DeviceId.
func (s *Device) SetDeviceId(val string) {
	s.DeviceId = val
}

// SetName sets the value of Name.
func (s *Device) SetName(val string) {
	s.Name = val
}

// SetGpuModel sets the value of GpuModel.
func (s *Device) SetGpuModel(val string) {
	s.GpuModel = val
}

// SetVramMb sets the value of VramMb.
func (s *Device) SetVramMb(val int) {
	s.VramMb = val
}

// SetCudaCores sets the value of CudaCores.
func (s *Device) SetCudaCores(val int) {
	s.CudaCores = val
}

// SetPricePerHourUsdCents sets the value of PricePerHourUsdCents.
func (s *Device) SetPricePerHourUsdCents(val int) {
	s.PricePerHourUsdCents = val
}

// SetDriverVersion sets the value of DriverVersion.
func (s *Device) SetDriverVersion(val string) {
	s.DriverVersion = val
}

// SetState sets the value of State.
func (s *Device) SetState(val State) {
	s.State = val
}

// Ref: #
type DeviceStatus struct {
	DeviceId           string    `json:"deviceId"`
	State              State     `json:"state"`
	TemperatureC       int       `json:"temperatureC"`
	UtilizationPercent int       `json:"utilizationPercent"`
	MemoryUsedMb       int       `json:"memoryUsedMb"`
	LastHeartbeat      time.Time `json:"lastHeartbeat"`
}

// GetDeviceId returns the value of DeviceId.
func (s *DeviceStatus) GetDeviceId() string {
	return s.DeviceId
}

// GetState returns the value of State.
func (s *DeviceStatus) GetState() State {
	return s.State
}

// GetTemperatureC returns the value of TemperatureC.
func (s *DeviceStatus) GetTemperatureC() int {
	return s.TemperatureC
}

// GetUtilizationPercent returns the value of UtilizationPercent.
func (s *DeviceStatus) GetUtilizationPercent() int {
	return s.UtilizationPercent
}

// GetMemoryUsedMb returns the value of MemoryUsedMb.
func (s *DeviceStatus) GetMemoryUsedMb() int {
	return s.MemoryUsedMb
}

// GetLastHeartbeat returns the value of LastHeartbeat.
func (s *DeviceStatus) GetLastHeartbeat() time.Time {
	return s.LastHeartbeat
}

// SetDeviceId sets the value of DeviceId.
func (s *DeviceStatus) SetDeviceId(val string) {
	s.DeviceId = val
}

// SetState sets the value of State.
func (s *DeviceStatus) SetState(val State) {
	s.State = val
}

// SetTemperatureC sets the value of TemperatureC.
func (s *DeviceStatus) SetTemperatureC(val int) {
	s.TemperatureC = val
}

// SetUtilizationPercent sets the value of UtilizationPercent.
func (s *DeviceStatus) SetUtilizationPercent(val int) {
	s.UtilizationPercent = val
}

// SetMemoryUsedMb sets the value of MemoryUsedMb.
func (s *DeviceStatus) SetMemoryUsedMb(val int) {
	s.MemoryUsedMb = val
}

// SetLastHeartbeat sets the value of LastHeartbeat.
func (s *DeviceStatus) SetLastHeartbeat(val time.Time) {
	s.LastHeartbeat = val
}

func (*DeviceStatus) getDeviceStatusRes() {}

type Error string

// GetDeviceStatusNotFound is response for GetDeviceStatus operation.
type GetDeviceStatusNotFound struct{}

func (*GetDeviceStatusNotFound) getDeviceStatusRes() {}

type GetDevicesBadRequest struct {
	ErrorMessage string `json:"errorMessage"`
}

// GetErrorMessage returns the value of ErrorMessage.
func (s *GetDevicesBadRequest) GetErrorMessage() string {
	return s.ErrorMessage
}

// SetErrorMessage sets the value of ErrorMessage.
func (s *GetDevicesBadRequest) SetErrorMessage(val string) {
	s.ErrorMessage = val
}

func (*GetDevicesBadRequest) getDevicesRes() {}

// GetDevicesNotFound is response for GetDevices operation.
type GetDevicesNotFound struct{}

func (*GetDevicesNotFound) getDevicesRes() {}

type GetDevicesOKApplicationJSON []Device

func (*GetDevicesOKApplicationJSON) getDevicesRes() {}

// GetHealthOK is response for GetHealth operation.
type GetHealthOK struct{}

// GetOrderByIdNotFound is response for GetOrderById operation.
type GetOrderByIdNotFound struct{}

func (*GetOrderByIdNotFound) getOrderByIdRes() {}

// GetOrderByIdUnauthorized is response for GetOrderById operation.
type GetOrderByIdUnauthorized struct{}

func (*GetOrderByIdUnauthorized) getOrderByIdRes() {}

// GetOrdersBadRequest is response for GetOrders operation.
type GetOrdersBadRequest struct{}

func (*GetOrdersBadRequest) getOrdersRes() {}

type GetOrdersOKApplicationJSON []Order

func (*GetOrdersOKApplicationJSON) getOrdersRes() {}

// GetOrdersUnauthorized is response for GetOrders operation.
type GetOrdersUnauthorized struct{}

func (*GetOrdersUnauthorized) getOrdersRes() {}

// GetReviewsByDeviceIdNotFound is response for GetReviewsByDeviceId operation.
type GetReviewsByDeviceIdNotFound struct{}

func (*GetReviewsByDeviceIdNotFound) getReviewsByDeviceIdRes() {}

type GetReviewsByDeviceIdOKApplicationJSON []Review

func (*GetReviewsByDeviceIdOKApplicationJSON) getReviewsByDeviceIdRes() {}

// GetReviewsByUsernameNotFound is response for GetReviewsByUsername operation.
type GetReviewsByUsernameNotFound struct{}

func (*GetReviewsByUsernameNotFound) getReviewsByUsernameRes() {}

type GetReviewsByUsernameOKApplicationJSON []Review

func (*GetReviewsByUsernameOKApplicationJSON) getReviewsByUsernameRes() {}

// GetUserRatingNotFound is response for GetUserRating operation.
type GetUserRatingNotFound struct{}

func (*GetUserRatingNotFound) getUserRatingRes() {}

type GetUserRatingOK struct {
	// The average rating score of the user.
	AverageRating float32 `json:"averageRating"`
	// The total number of reviews submitted for this user.
	RatingCount int `json:"ratingCount"`
}

// GetAverageRating returns the value of AverageRating.
func (s *GetUserRatingOK) GetAverageRating() float32 {
	return s.AverageRating
}

// GetRatingCount returns the value of RatingCount.
func (s *GetUserRatingOK) GetRatingCount() int {
	return s.RatingCount
}

// SetAverageRating sets the value of AverageRating.
func (s *GetUserRatingOK) SetAverageRating(val float32) {
	s.AverageRating = val
}

// SetRatingCount sets the value of RatingCount.
func (s *GetUserRatingOK) SetRatingCount(val int) {
	s.RatingCount = val
}

func (*GetUserRatingOK) getUserRatingRes() {}

// LoginNotFound is response for Login operation.
type LoginNotFound struct{}

func (*LoginNotFound) loginRes() {}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

// GetUsername returns the value of Username.
func (s *LoginReq) GetUsername() string {
	return s.Username
}

// GetPassword returns the value of Password.
func (s *LoginReq) GetPassword() string {
	return s.Password
}

// SetUsername sets the value of Username.
func (s *LoginReq) SetUsername(val string) {
	s.Username = val
}

// SetPassword sets the value of Password.
func (s *LoginReq) SetPassword(val string) {
	s.Password = val
}

// LoginUnauthorized is response for Login operation.
type LoginUnauthorized struct{}

func (*LoginUnauthorized) loginRes() {}

// NewOptInt returns new OptInt with value set to v.
func NewOptInt(v int) OptInt {
	return OptInt{
		Value: v,
		Set:   true,
	}
}

// OptInt is optional int.
type OptInt struct {
	Value int
	Set   bool
}

// IsSet returns true if OptInt was set.
func (o OptInt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt) Reset() {
	var v int
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt) SetTo(v int) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt) Get() (v int, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt) Or(d int) int {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #
type Order struct {
	OrderId                string            `json:"orderId"`
	Status                 RentalStatus      `json:"status"`
	ConnectionDetails      ConnectionDetails `json:"connectionDetails"`
	TotalReservedCostCents int               `json:"totalReservedCostCents"`
}

// GetOrderId returns the value of OrderId.
func (s *Order) GetOrderId() string {
	return s.OrderId
}

// GetStatus returns the value of Status.
func (s *Order) GetStatus() RentalStatus {
	return s.Status
}

// GetConnectionDetails returns the value of ConnectionDetails.
func (s *Order) GetConnectionDetails() ConnectionDetails {
	return s.ConnectionDetails
}

// GetTotalReservedCostCents returns the value of TotalReservedCostCents.
func (s *Order) GetTotalReservedCostCents() int {
	return s.TotalReservedCostCents
}

// SetOrderId sets the value of OrderId.
func (s *Order) SetOrderId(val string) {
	s.OrderId = val
}

// SetStatus sets the value of Status.
func (s *Order) SetStatus(val RentalStatus) {
	s.Status = val
}

// SetConnectionDetails sets the value of ConnectionDetails.
func (s *Order) SetConnectionDetails(val ConnectionDetails) {
	s.ConnectionDetails = val
}

// SetTotalReservedCostCents sets the value of TotalReservedCostCents.
func (s *Order) SetTotalReservedCostCents(val int) {
	s.TotalReservedCostCents = val
}

func (*Order) getOrderByIdRes() {}
func (*Order) orderDeviceRes()  {}

// OrderDeviceBadRequest is response for OrderDevice operation.
type OrderDeviceBadRequest struct{}

func (*OrderDeviceBadRequest) orderDeviceRes() {}

// OrderDevicePaymentRequired is response for OrderDevice operation.
type OrderDevicePaymentRequired struct{}

func (*OrderDevicePaymentRequired) orderDeviceRes() {}

type OrderDeviceReq struct {
	// Id of device to rent.
	DeviceId string `json:"deviceId"`
	// Name of Docker image to run on the device.
	DockerImage string `json:"dockerImage"`
	// Maximum execution duration in hours as a double-precision floating number. The minimum is 0.0002
	// (slightly less than 1 second).
	DurationHours float64 `json:"durationHours"`
}

// GetDeviceId returns the value of DeviceId.
func (s *OrderDeviceReq) GetDeviceId() string {
	return s.DeviceId
}

// GetDockerImage returns the value of DockerImage.
func (s *OrderDeviceReq) GetDockerImage() string {
	return s.DockerImage
}

// GetDurationHours returns the value of DurationHours.
func (s *OrderDeviceReq) GetDurationHours() float64 {
	return s.DurationHours
}

// SetDeviceId sets the value of DeviceId.
func (s *OrderDeviceReq) SetDeviceId(val string) {
	s.DeviceId = val
}

// SetDockerImage sets the value of DockerImage.
func (s *OrderDeviceReq) SetDockerImage(val string) {
	s.DockerImage = val
}

// SetDurationHours sets the value of DurationHours.
func (s *OrderDeviceReq) SetDurationHours(val float64) {
	s.DurationHours = val
}

// RefreshUnauthorized is response for Refresh operation.
type RefreshUnauthorized struct{}

func (*RefreshUnauthorized) refreshRes() {}

type RegisterBadRequestApplicationJSON string

func (*RegisterBadRequestApplicationJSON) registerRes() {}

// RegisterConflict is response for Register operation.
type RegisterConflict struct{}

func (*RegisterConflict) registerRes() {}

type RegisterReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

// GetUsername returns the value of Username.
func (s *RegisterReq) GetUsername() string {
	return s.Username
}

// GetPassword returns the value of Password.
func (s *RegisterReq) GetPassword() string {
	return s.Password
}

// SetUsername sets the value of Username.
func (s *RegisterReq) SetUsername(val string) {
	s.Username = val
}

// SetPassword sets the value of Password.
func (s *RegisterReq) SetPassword(val string) {
	s.Password = val
}

// Ref: #
type RentalStatus string

const (
	RentalStatusWAITINGFORSTART RentalStatus = "WAITING_FOR_START"
	RentalStatusRUNNING         RentalStatus = "RUNNING"
	RentalStatusCOMPLETED       RentalStatus = "COMPLETED"
	RentalStatusSUSPENDED       RentalStatus = "SUSPENDED"
	RentalStatusFAILURE         RentalStatus = "FAILURE"
)

// AllValues returns all RentalStatus values.
func (RentalStatus) AllValues() []RentalStatus {
	return []RentalStatus{
		RentalStatusWAITINGFORSTART,
		RentalStatusRUNNING,
		RentalStatusCOMPLETED,
		RentalStatusSUSPENDED,
		RentalStatusFAILURE,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s RentalStatus) MarshalText() ([]byte, error) {
	switch s {
	case RentalStatusWAITINGFORSTART:
		return []byte(s), nil
	case RentalStatusRUNNING:
		return []byte(s), nil
	case RentalStatusCOMPLETED:
		return []byte(s), nil
	case RentalStatusSUSPENDED:
		return []byte(s), nil
	case RentalStatusFAILURE:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *RentalStatus) UnmarshalText(data []byte) error {
	switch RentalStatus(data) {
	case RentalStatusWAITINGFORSTART:
		*s = RentalStatusWAITINGFORSTART
		return nil
	case RentalStatusRUNNING:
		*s = RentalStatusRUNNING
		return nil
	case RentalStatusCOMPLETED:
		*s = RentalStatusCOMPLETED
		return nil
	case RentalStatusSUSPENDED:
		*s = RentalStatusSUSPENDED
		return nil
	case RentalStatusFAILURE:
		*s = RentalStatusFAILURE
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #
type Review struct {
	// The unique identifier of the review.
	ReviewId int `json:"reviewId"`
	// The unique identifier of the associated order.
	OrderId string `json:"orderId"`
	// Username of the user who wrote the review.
	AuthorUsername string `json:"authorUsername"`
	// The rating score given by the user.
	Rating int `json:"rating"`
	// Feedback details.
	Comment OptString `json:"comment"`
	// The timestamp when the review was created.
	CreatedAt time.Time `json:"createdAt"`
}

// GetReviewId returns the value of ReviewId.
func (s *Review) GetReviewId() int {
	return s.ReviewId
}

// GetOrderId returns the value of OrderId.
func (s *Review) GetOrderId() string {
	return s.OrderId
}

// GetAuthorUsername returns the value of AuthorUsername.
func (s *Review) GetAuthorUsername() string {
	return s.AuthorUsername
}

// GetRating returns the value of Rating.
func (s *Review) GetRating() int {
	return s.Rating
}

// GetComment returns the value of Comment.
func (s *Review) GetComment() OptString {
	return s.Comment
}

// GetCreatedAt returns the value of CreatedAt.
func (s *Review) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// SetReviewId sets the value of ReviewId.
func (s *Review) SetReviewId(val int) {
	s.ReviewId = val
}

// SetOrderId sets the value of OrderId.
func (s *Review) SetOrderId(val string) {
	s.OrderId = val
}

// SetAuthorUsername sets the value of AuthorUsername.
func (s *Review) SetAuthorUsername(val string) {
	s.AuthorUsername = val
}

// SetRating sets the value of Rating.
func (s *Review) SetRating(val int) {
	s.Rating = val
}

// SetComment sets the value of Comment.
func (s *Review) SetComment(val OptString) {
	s.Comment = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *Review) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

// ReviewOrderByIdBadRequest is response for ReviewOrderById operation.
type ReviewOrderByIdBadRequest struct{}

func (*ReviewOrderByIdBadRequest) reviewOrderByIdRes() {}

// ReviewOrderByIdConflict is response for ReviewOrderById operation.
type ReviewOrderByIdConflict struct{}

func (*ReviewOrderByIdConflict) reviewOrderByIdRes() {}

type ReviewOrderByIdCreated struct {
	// The unique identifier of the newly created review.
	ReviewId int `json:"reviewId"`
	// Username of the currently authenticated user who wrote the review.
	AuthorUsername string `json:"authorUsername"`
	// The timestamp when the review was created.
	CreatedAt time.Time `json:"createdAt"`
}

// GetReviewId returns the value of ReviewId.
func (s *ReviewOrderByIdCreated) GetReviewId() int {
	return s.ReviewId
}

// GetAuthorUsername returns the value of AuthorUsername.
func (s *ReviewOrderByIdCreated) GetAuthorUsername() string {
	return s.AuthorUsername
}

// GetCreatedAt returns the value of CreatedAt.
func (s *ReviewOrderByIdCreated) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// SetReviewId sets the value of ReviewId.
func (s *ReviewOrderByIdCreated) SetReviewId(val int) {
	s.ReviewId = val
}

// SetAuthorUsername sets the value of AuthorUsername.
func (s *ReviewOrderByIdCreated) SetAuthorUsername(val string) {
	s.AuthorUsername = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *ReviewOrderByIdCreated) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

func (*ReviewOrderByIdCreated) reviewOrderByIdRes() {}

type ReviewOrderByIdReq struct {
	// The rating score given by the user (from 1 to 5).
	Rating int `json:"rating"`
	// Detailed feedback from the user.
	Comment string `json:"comment"`
}

// GetRating returns the value of Rating.
func (s *ReviewOrderByIdReq) GetRating() int {
	return s.Rating
}

// GetComment returns the value of Comment.
func (s *ReviewOrderByIdReq) GetComment() string {
	return s.Comment
}

// SetRating sets the value of Rating.
func (s *ReviewOrderByIdReq) SetRating(val int) {
	s.Rating = val
}

// SetComment sets the value of Comment.
func (s *ReviewOrderByIdReq) SetComment(val string) {
	s.Comment = val
}

// ReviewOrderByIdUnauthorized is response for ReviewOrderById operation.
type ReviewOrderByIdUnauthorized struct{}

func (*ReviewOrderByIdUnauthorized) reviewOrderByIdRes() {}

// Ref: #
type State string

const (
	StateAVAILABLE   State = "AVAILABLE"
	StateUNAVAILABLE State = "UNAVAILABLE"
	StateRENTED      State = "RENTED"
	StateREPORTED    State = "REPORTED"
)

// AllValues returns all State values.
func (State) AllValues() []State {
	return []State{
		StateAVAILABLE,
		StateUNAVAILABLE,
		StateRENTED,
		StateREPORTED,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s State) MarshalText() ([]byte, error) {
	switch s {
	case StateAVAILABLE:
		return []byte(s), nil
	case StateUNAVAILABLE:
		return []byte(s), nil
	case StateRENTED:
		return []byte(s), nil
	case StateREPORTED:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *State) UnmarshalText(data []byte) error {
	switch State(data) {
	case StateAVAILABLE:
		*s = StateAVAILABLE
		return nil
	case StateUNAVAILABLE:
		*s = StateUNAVAILABLE
		return nil
	case StateRENTED:
		*s = StateRENTED
		return nil
	case StateREPORTED:
		*s = StateREPORTED
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}
