// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// GetDeviceStatus implements getDeviceStatus operation.
	//
	// Get device status by ID.
	//
	// GET /api/devices/{deviceId}/status
	GetDeviceStatus(ctx context.Context, params GetDeviceStatusParams) (GetDeviceStatusRes, error)
	// GetDevices implements getDevices operation.
	//
	// Get list of devices that match the provided filters.
	//
	// GET /api/devices
	GetDevices(ctx context.Context, params GetDevicesParams) (GetDevicesRes, error)
	// GetHealth implements getHealth operation.
	//
	// Check if server is up.
	//
	// GET /health
	GetHealth(ctx context.Context) (*GetHealthOKHeaders, error)
	// NewError creates *ErrorStatusCode from error returned by handler.
	//
	// Used for common default response.
	NewError(ctx context.Context, err error) *ErrorStatusCode
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
