// Code generated by ogen, DO NOT EDIT.

package api

import (
	"io"
	"time"

	"github.com/go-faster/errors"
)

// Ref: #
type DeviceStatus struct {
	DeviceId           string            `json:"deviceId"`
	State              DeviceStatusState `json:"state"`
	TemperatureC       int               `json:"temperatureC"`
	UtilizationPercent int               `json:"utilizationPercent"`
	MemoryUsedMb       int               `json:"memoryUsedMb"`
	LastHeartbeat      time.Time         `json:"lastHeartbeat"`
}

// GetDeviceId returns the value of DeviceId.
func (s *DeviceStatus) GetDeviceId() string {
	return s.DeviceId
}

// GetState returns the value of State.
func (s *DeviceStatus) GetState() DeviceStatusState {
	return s.State
}

// GetTemperatureC returns the value of TemperatureC.
func (s *DeviceStatus) GetTemperatureC() int {
	return s.TemperatureC
}

// GetUtilizationPercent returns the value of UtilizationPercent.
func (s *DeviceStatus) GetUtilizationPercent() int {
	return s.UtilizationPercent
}

// GetMemoryUsedMb returns the value of MemoryUsedMb.
func (s *DeviceStatus) GetMemoryUsedMb() int {
	return s.MemoryUsedMb
}

// GetLastHeartbeat returns the value of LastHeartbeat.
func (s *DeviceStatus) GetLastHeartbeat() time.Time {
	return s.LastHeartbeat
}

// SetDeviceId sets the value of DeviceId.
func (s *DeviceStatus) SetDeviceId(val string) {
	s.DeviceId = val
}

// SetState sets the value of State.
func (s *DeviceStatus) SetState(val DeviceStatusState) {
	s.State = val
}

// SetTemperatureC sets the value of TemperatureC.
func (s *DeviceStatus) SetTemperatureC(val int) {
	s.TemperatureC = val
}

// SetUtilizationPercent sets the value of UtilizationPercent.
func (s *DeviceStatus) SetUtilizationPercent(val int) {
	s.UtilizationPercent = val
}

// SetMemoryUsedMb sets the value of MemoryUsedMb.
func (s *DeviceStatus) SetMemoryUsedMb(val int) {
	s.MemoryUsedMb = val
}

// SetLastHeartbeat sets the value of LastHeartbeat.
func (s *DeviceStatus) SetLastHeartbeat(val time.Time) {
	s.LastHeartbeat = val
}

func (*DeviceStatus) getDeviceStatusRes() {}

type DeviceStatusState string

const (
	DeviceStatusStateAVAILABLE   DeviceStatusState = "AVAILABLE"
	DeviceStatusStateUNAVAILABLE DeviceStatusState = "UNAVAILABLE"
	DeviceStatusStateRENTED      DeviceStatusState = "RENTED"
	DeviceStatusStateREPORTED    DeviceStatusState = "REPORTED"
)

// AllValues returns all DeviceStatusState values.
func (DeviceStatusState) AllValues() []DeviceStatusState {
	return []DeviceStatusState{
		DeviceStatusStateAVAILABLE,
		DeviceStatusStateUNAVAILABLE,
		DeviceStatusStateRENTED,
		DeviceStatusStateREPORTED,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s DeviceStatusState) MarshalText() ([]byte, error) {
	switch s {
	case DeviceStatusStateAVAILABLE:
		return []byte(s), nil
	case DeviceStatusStateUNAVAILABLE:
		return []byte(s), nil
	case DeviceStatusStateRENTED:
		return []byte(s), nil
	case DeviceStatusStateREPORTED:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *DeviceStatusState) UnmarshalText(data []byte) error {
	switch DeviceStatusState(data) {
	case DeviceStatusStateAVAILABLE:
		*s = DeviceStatusStateAVAILABLE
		return nil
	case DeviceStatusStateUNAVAILABLE:
		*s = DeviceStatusStateUNAVAILABLE
		return nil
	case DeviceStatusStateRENTED:
		*s = DeviceStatusStateRENTED
		return nil
	case DeviceStatusStateREPORTED:
		*s = DeviceStatusStateREPORTED
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// GetDeviceStatusNotFound is response for GetDeviceStatus operation.
type GetDeviceStatusNotFound struct{}

func (*GetDeviceStatusNotFound) getDeviceStatusRes() {}

type GetHealthOK struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s GetHealthOK) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

// GetHealthOKHeaders wraps GetHealthOK with response headers.
type GetHealthOKHeaders struct {
	ContentType string
	Response    GetHealthOK
}

// GetContentType returns the value of ContentType.
func (s *GetHealthOKHeaders) GetContentType() string {
	return s.ContentType
}

// GetResponse returns the value of Response.
func (s *GetHealthOKHeaders) GetResponse() GetHealthOK {
	return s.Response
}

// SetContentType sets the value of ContentType.
func (s *GetHealthOKHeaders) SetContentType(val string) {
	s.ContentType = val
}

// SetResponse sets the value of Response.
func (s *GetHealthOKHeaders) SetResponse(val GetHealthOK) {
	s.Response = val
}
