// Code generated by ogen, DO NOT EDIT.

package api

import (
	"fmt"
	"net/http"
	"net/url"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// GetDeviceStatusParams is parameters of getDeviceStatus operation.
type GetDeviceStatusParams struct {
	// The id of device to retrieve.
	DeviceId string
}

func unpackGetDeviceStatusParams(packed middleware.Parameters) (params GetDeviceStatusParams) {
	{
		key := middleware.ParameterKey{
			Name: "deviceId",
			In:   "path",
		}
		params.DeviceId = packed[key].(string)
	}
	return params
}

func decodeGetDeviceStatusParams(args [1]string, argsEscaped bool, r *http.Request) (params GetDeviceStatusParams, _ error) {
	// Decode path: deviceId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "deviceId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.DeviceId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "deviceId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetDevicesParams is parameters of getDevices operation.
type GetDevicesParams struct {
	// Maximum number of elements to retrieve.
	Limit OptInt `json:",omitempty,omitzero"`
	// Name of devices to retrieve.
	Name OptString `json:",omitempty,omitzero"`
	// Model of device to retrieve.
	GpuModel OptString `json:",omitempty,omitzero"`
	// Minimum amount of Video RAM in megabytes.
	MinVramMb OptInt `json:",omitempty,omitzero"`
	// Maximum amount of Video RAM in megabytes.
	MaxVramMb OptInt `json:",omitempty,omitzero"`
	// Minimum amount of CUDA cores.
	MinCudaCores OptInt `json:",omitempty,omitzero"`
	// Maximum amount of CUDA cores.
	MaxCudaCores OptInt `json:",omitempty,omitzero"`
	// Minimum price per hour of device usage in USD cents.
	MinPricePerHourUsdCents OptInt `json:",omitempty,omitzero"`
	// Maximum price per hour of device usage in USD cents.
	MaxPricePerHourUsdCents OptInt `json:",omitempty,omitzero"`
	// Minimum driver version.
	MinDriverVersion OptString `json:",omitempty,omitzero"`
	// Maximum driver version.
	MaxDriverVersion OptString `json:",omitempty,omitzero"`
	// Device states.
	States []State `json:",omitempty"`
}

func unpackGetDevicesParams(packed middleware.Parameters) (params GetDevicesParams) {
	{
		key := middleware.ParameterKey{
			Name: "limit",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Limit = v.(OptInt)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "name",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Name = v.(OptString)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "gpuModel",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.GpuModel = v.(OptString)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "minVramMb",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.MinVramMb = v.(OptInt)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "maxVramMb",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.MaxVramMb = v.(OptInt)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "minCudaCores",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.MinCudaCores = v.(OptInt)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "maxCudaCores",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.MaxCudaCores = v.(OptInt)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "minPricePerHourUsdCents",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.MinPricePerHourUsdCents = v.(OptInt)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "maxPricePerHourUsdCents",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.MaxPricePerHourUsdCents = v.(OptInt)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "minDriverVersion",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.MinDriverVersion = v.(OptString)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "maxDriverVersion",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.MaxDriverVersion = v.(OptString)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "states",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.States = v.([]State)
		}
	}
	return params
}

func decodeGetDevicesParams(args [0]string, argsEscaped bool, r *http.Request) (params GetDevicesParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Set default value for query: limit.
	{
		val := int(25)
		params.Limit.SetTo(val)
	}
	// Decode query: limit.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "limit",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotLimitVal int
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToInt(val)
					if err != nil {
						return err
					}

					paramsDotLimitVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Limit.SetTo(paramsDotLimitVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.Limit.Get(); ok {
					if err := func() error {
						if err := (validate.Int{
							MinSet:        true,
							Min:           1,
							MaxSet:        true,
							Max:           200,
							MinExclusive:  false,
							MaxExclusive:  false,
							MultipleOfSet: false,
							MultipleOf:    0,
							Pattern:       nil,
						}).Validate(int64(value)); err != nil {
							return errors.Wrap(err, "int")
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "limit",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: name.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "name",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotNameVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotNameVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Name.SetTo(paramsDotNameVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "name",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: gpuModel.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "gpuModel",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotGpuModelVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotGpuModelVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.GpuModel.SetTo(paramsDotGpuModelVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "gpuModel",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: minVramMb.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "minVramMb",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotMinVramMbVal int
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToInt(val)
					if err != nil {
						return err
					}

					paramsDotMinVramMbVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.MinVramMb.SetTo(paramsDotMinVramMbVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.MinVramMb.Get(); ok {
					if err := func() error {
						if err := (validate.Int{
							MinSet:        true,
							Min:           0,
							MaxSet:        false,
							Max:           0,
							MinExclusive:  false,
							MaxExclusive:  false,
							MultipleOfSet: false,
							MultipleOf:    0,
							Pattern:       nil,
						}).Validate(int64(value)); err != nil {
							return errors.Wrap(err, "int")
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "minVramMb",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: maxVramMb.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "maxVramMb",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotMaxVramMbVal int
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToInt(val)
					if err != nil {
						return err
					}

					paramsDotMaxVramMbVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.MaxVramMb.SetTo(paramsDotMaxVramMbVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.MaxVramMb.Get(); ok {
					if err := func() error {
						if err := (validate.Int{
							MinSet:        true,
							Min:           0,
							MaxSet:        false,
							Max:           0,
							MinExclusive:  false,
							MaxExclusive:  false,
							MultipleOfSet: false,
							MultipleOf:    0,
							Pattern:       nil,
						}).Validate(int64(value)); err != nil {
							return errors.Wrap(err, "int")
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "maxVramMb",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: minCudaCores.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "minCudaCores",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotMinCudaCoresVal int
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToInt(val)
					if err != nil {
						return err
					}

					paramsDotMinCudaCoresVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.MinCudaCores.SetTo(paramsDotMinCudaCoresVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.MinCudaCores.Get(); ok {
					if err := func() error {
						if err := (validate.Int{
							MinSet:        true,
							Min:           0,
							MaxSet:        false,
							Max:           0,
							MinExclusive:  false,
							MaxExclusive:  false,
							MultipleOfSet: false,
							MultipleOf:    0,
							Pattern:       nil,
						}).Validate(int64(value)); err != nil {
							return errors.Wrap(err, "int")
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "minCudaCores",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: maxCudaCores.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "maxCudaCores",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotMaxCudaCoresVal int
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToInt(val)
					if err != nil {
						return err
					}

					paramsDotMaxCudaCoresVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.MaxCudaCores.SetTo(paramsDotMaxCudaCoresVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.MaxCudaCores.Get(); ok {
					if err := func() error {
						if err := (validate.Int{
							MinSet:        true,
							Min:           0,
							MaxSet:        false,
							Max:           0,
							MinExclusive:  false,
							MaxExclusive:  false,
							MultipleOfSet: false,
							MultipleOf:    0,
							Pattern:       nil,
						}).Validate(int64(value)); err != nil {
							return errors.Wrap(err, "int")
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "maxCudaCores",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: minPricePerHourUsdCents.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "minPricePerHourUsdCents",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotMinPricePerHourUsdCentsVal int
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToInt(val)
					if err != nil {
						return err
					}

					paramsDotMinPricePerHourUsdCentsVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.MinPricePerHourUsdCents.SetTo(paramsDotMinPricePerHourUsdCentsVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.MinPricePerHourUsdCents.Get(); ok {
					if err := func() error {
						if err := (validate.Int{
							MinSet:        true,
							Min:           0,
							MaxSet:        false,
							Max:           0,
							MinExclusive:  false,
							MaxExclusive:  false,
							MultipleOfSet: false,
							MultipleOf:    0,
							Pattern:       nil,
						}).Validate(int64(value)); err != nil {
							return errors.Wrap(err, "int")
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "minPricePerHourUsdCents",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: maxPricePerHourUsdCents.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "maxPricePerHourUsdCents",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotMaxPricePerHourUsdCentsVal int
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToInt(val)
					if err != nil {
						return err
					}

					paramsDotMaxPricePerHourUsdCentsVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.MaxPricePerHourUsdCents.SetTo(paramsDotMaxPricePerHourUsdCentsVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.MaxPricePerHourUsdCents.Get(); ok {
					if err := func() error {
						if err := (validate.Int{
							MinSet:        true,
							Min:           0,
							MaxSet:        false,
							Max:           0,
							MinExclusive:  false,
							MaxExclusive:  false,
							MultipleOfSet: false,
							MultipleOf:    0,
							Pattern:       nil,
						}).Validate(int64(value)); err != nil {
							return errors.Wrap(err, "int")
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "maxPricePerHourUsdCents",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: minDriverVersion.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "minDriverVersion",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotMinDriverVersionVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotMinDriverVersionVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.MinDriverVersion.SetTo(paramsDotMinDriverVersionVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "minDriverVersion",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: maxDriverVersion.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "maxDriverVersion",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotMaxDriverVersionVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotMaxDriverVersionVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.MaxDriverVersion.SetTo(paramsDotMaxDriverVersionVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "maxDriverVersion",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: states.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "states",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				return d.DecodeArray(func(d uri.Decoder) error {
					var paramsDotStatesVal State
					if err := func() error {
						val, err := d.DecodeValue()
						if err != nil {
							return err
						}

						c, err := conv.ToString(val)
						if err != nil {
							return err
						}

						paramsDotStatesVal = State(c)
						return nil
					}(); err != nil {
						return err
					}
					params.States = append(params.States, paramsDotStatesVal)
					return nil
				})
			}); err != nil {
				return err
			}
			if err := func() error {
				if params.States == nil {
					return nil // optional
				}
				if err := (validate.Array{
					MinLength:    1,
					MinLengthSet: true,
					MaxLength:    0,
					MaxLengthSet: false,
				}).ValidateLength(len(params.States)); err != nil {
					return errors.Wrap(err, "array")
				}
				var failures []validate.FieldError
				for i, elem := range params.States {
					if err := func() error {
						if err := elem.Validate(); err != nil {
							return err
						}
						return nil
					}(); err != nil {
						failures = append(failures, validate.FieldError{
							Name:  fmt.Sprintf("[%d]", i),
							Error: err,
						})
					}
				}
				if len(failures) > 0 {
					return &validate.Error{Fields: failures}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "states",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}

// OrderDeviceParams is parameters of orderDevice operation.
type OrderDeviceParams struct {
	// Id of device to rent.
	DeviceId string
	// Name of Docker image to run on the device.
	DockerImage string
	// Maximum execution duration in hours as a double-precision floating number. The minimum is 0.0002
	// (slightly less than 1 second).
	DurationHours float64
}

func unpackOrderDeviceParams(packed middleware.Parameters) (params OrderDeviceParams) {
	{
		key := middleware.ParameterKey{
			Name: "deviceId",
			In:   "query",
		}
		params.DeviceId = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "dockerImage",
			In:   "query",
		}
		params.DockerImage = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "durationHours",
			In:   "query",
		}
		params.DurationHours = packed[key].(float64)
	}
	return params
}

func decodeOrderDeviceParams(args [0]string, argsEscaped bool, r *http.Request) (params OrderDeviceParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: deviceId.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "deviceId",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.DeviceId = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "deviceId",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: dockerImage.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "dockerImage",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.DockerImage = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "dockerImage",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: durationHours.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "durationHours",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToFloat64(val)
				if err != nil {
					return err
				}

				params.DurationHours = c
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if err := (validate.Float{
					MinSet:        true,
					Min:           0.0002,
					MaxSet:        false,
					Max:           0,
					MinExclusive:  false,
					MaxExclusive:  false,
					MultipleOfSet: false,
					MultipleOf:    nil,
					Pattern:       nil,
				}).Validate(float64(params.DurationHours)); err != nil {
					return errors.Wrap(err, "float")
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "durationHours",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}
