// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	GetDeviceStatusOperation OperationName = "GetDeviceStatus"
	GetHealthOperation       OperationName = "GetHealth"
)
