// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// AddTask implements addTask operation.
	//
	// Schedule a task on a given device.
	//
	// POST /api/jobs
	AddTask(ctx context.Context, req *AddTaskReq) (AddTaskRes, error)
	// GetHealth implements getHealth operation.
	//
	// Check if server is up.
	//
	// GET /health
	GetHealth(ctx context.Context) (*GetHealthOKHeaders, error)
	// NewError creates *ErrorStatusCode from error returned by handler.
	//
	// Used for common default response.
	NewError(ctx context.Context, err error) *ErrorStatusCode
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
