// Code generated by ogen, DO NOT EDIT.

package api

import (
	"fmt"
	"io"
)

func (s *ErrorStatusCode) Error() string {
	return fmt.Sprintf("code %d: %+v", s.StatusCode, s.Response)
}

// AddTaskBadRequest is response for AddTask operation.
type AddTaskBadRequest struct{}

func (*AddTaskBadRequest) addTaskRes() {}

type AddTaskCreated struct {
	JobId string `json:"jobId"`
}

// GetJobId returns the value of JobId.
func (s *AddTaskCreated) GetJobId() string {
	return s.JobId
}

// SetJobId sets the value of JobId.
func (s *AddTaskCreated) SetJobId(val string) {
	s.JobId = val
}

func (*AddTaskCreated) addTaskRes() {}

type AddTaskReq struct {
	Resources Resources `json:"resources"`
	// Optional time in seconds after which the job will be terminated.
	MaxTimeSec OptInt `json:"maxTimeSec"`
}

// GetResources returns the value of Resources.
func (s *AddTaskReq) GetResources() Resources {
	return s.Resources
}

// GetMaxTimeSec returns the value of MaxTimeSec.
func (s *AddTaskReq) GetMaxTimeSec() OptInt {
	return s.MaxTimeSec
}

// SetResources sets the value of Resources.
func (s *AddTaskReq) SetResources(val Resources) {
	s.Resources = val
}

// SetMaxTimeSec sets the value of MaxTimeSec.
func (s *AddTaskReq) SetMaxTimeSec(val OptInt) {
	s.MaxTimeSec = val
}

type Error string

// ErrorStatusCode wraps Error with StatusCode.
type ErrorStatusCode struct {
	StatusCode int
	Response   Error
}

// GetStatusCode returns the value of StatusCode.
func (s *ErrorStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *ErrorStatusCode) GetResponse() Error {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *ErrorStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *ErrorStatusCode) SetResponse(val Error) {
	s.Response = val
}

type GetHealthOK struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s GetHealthOK) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

// GetHealthOKHeaders wraps GetHealthOK with response headers.
type GetHealthOKHeaders struct {
	ContentType string
	Response    GetHealthOK
}

// GetContentType returns the value of ContentType.
func (s *GetHealthOKHeaders) GetContentType() string {
	return s.ContentType
}

// GetResponse returns the value of Response.
func (s *GetHealthOKHeaders) GetResponse() GetHealthOK {
	return s.Response
}

// SetContentType sets the value of ContentType.
func (s *GetHealthOKHeaders) SetContentType(val string) {
	s.ContentType = val
}

// SetResponse sets the value of Response.
func (s *GetHealthOKHeaders) SetResponse(val GetHealthOK) {
	s.Response = val
}

// NewOptInt returns new OptInt with value set to v.
func NewOptInt(v int) OptInt {
	return OptInt{
		Value: v,
		Set:   true,
	}
}

// OptInt is optional int.
type OptInt struct {
	Value int
	Set   bool
}

// IsSet returns true if OptInt was set.
func (o OptInt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt) Reset() {
	var v int
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt) SetTo(v int) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt) Get() (v int, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt) Or(d int) int {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #
type Resources struct {
	VRamMb OptInt `json:"vRamMb"`
}

// GetVRamMb returns the value of VRamMb.
func (s *Resources) GetVRamMb() OptInt {
	return s.VRamMb
}

// SetVRamMb sets the value of VRamMb.
func (s *Resources) SetVRamMb(val OptInt) {
	s.VRamMb = val
}
