// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	AddTaskOperation   OperationName = "AddTask"
	GetHealthOperation OperationName = "GetHealth"
)
