// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// GetAgentStatus implements getAgentStatus operation.
	//
	// Get agent's status.
	//
	// GET /api/agents/{agentId}/status
	GetAgentStatus(ctx context.Context, params GetAgentStatusParams) (GetAgentStatusRes, error)
	// GetHealth implements getHealth operation.
	//
	// Check if server is up.
	//
	// GET /health
	GetHealth(ctx context.Context) error
	// ScheduleTask implements scheduleTask operation.
	//
	// Schedule a task on a given device.
	//
	// POST /api/jobs
	ScheduleTask(ctx context.Context, req *ScheduleTaskReq) (ScheduleTaskRes, error)
	// NewError creates *DefaultStatusCode from error returned by handler.
	//
	// Used for common default response.
	NewError(ctx context.Context, err error) *DefaultStatusCode
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
