// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	GetAgentStatusOperation OperationName = "GetAgentStatus"
	GetHealthOperation      OperationName = "GetHealth"
	ScheduleTaskOperation   OperationName = "ScheduleTask"
)
