// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// GetAgentStatus implements getAgentStatus operation.
//
// Get agent's status.
//
// GET /api/agents/{agentId}/status
func (UnimplementedHandler) GetAgentStatus(ctx context.Context, params GetAgentStatusParams) (r GetAgentStatusRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetHealth implements getHealth operation.
//
// Check if server is up.
//
// GET /health
func (UnimplementedHandler) GetHealth(ctx context.Context) (r *GetHealthOKHeaders, _ error) {
	return r, ht.ErrNotImplemented
}

// ScheduleTask implements scheduleTask operation.
//
// Schedule a task on a given device.
//
// POST /api/jobs
func (UnimplementedHandler) ScheduleTask(ctx context.Context, req *ScheduleTaskReq) (r ScheduleTaskRes, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *ErrorStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *ErrorStatusCode) {
	r = new(ErrorStatusCode)
	return r
}
