// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
	"net/http"
	"strings"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/ogenerrors"
)

// SecurityHandler is handler for security parameters.
type SecurityHandler interface {
	// HandleCoordinatorApiKey handles CoordinatorApiKey security.
	// Secret key used only for backend -> coordinator communication.
	HandleCoordinatorApiKey(ctx context.Context, operationName OperationName, t CoordinatorApiKey) (context.Context, error)
}

func findAuthorization(h http.Header, prefix string) (string, bool) {
	v, ok := h["Authorization"]
	if !ok {
		return "", false
	}
	for _, vv := range v {
		scheme, value, ok := strings.Cut(vv, " ")
		if !ok || !strings.EqualFold(scheme, prefix) {
			continue
		}
		return value, true
	}
	return "", false
}

// operationRolesCoordinatorApiKey is a private map storing roles per operation.
var operationRolesCoordinatorApiKey = map[string][]string{
	GetAgentStatusOperation: []string{},
	GetHealthOperation:      []string{},
	ScheduleTaskOperation:   []string{},
}

// GetRolesForCoordinatorApiKey returns the required roles for the given operation.
//
// This is useful for authorization scenarios where you need to know which roles
// are required for an operation.
//
// Example:
//
//	requiredRoles := GetRolesForCoordinatorApiKey(AddPetOperation)
//
// Returns nil if the operation has no role requirements or if the operation is unknown.
func GetRolesForCoordinatorApiKey(operation string) []string {
	roles, ok := operationRolesCoordinatorApiKey[operation]
	if !ok {
		return nil
	}
	// Return a copy to prevent external modification
	result := make([]string, len(roles))
	copy(result, roles)
	return result
}

func (s *Server) securityCoordinatorApiKey(ctx context.Context, operationName OperationName, req *http.Request) (context.Context, bool, error) {
	var t CoordinatorApiKey
	const parameterName = "Authorization"
	value := req.Header.Get(parameterName)
	if value == "" {
		return ctx, false, nil
	}
	t.APIKey = value
	t.Roles = operationRolesCoordinatorApiKey[operationName]
	rctx, err := s.sec.HandleCoordinatorApiKey(ctx, operationName, t)
	if errors.Is(err, ogenerrors.ErrSkipServerSecurity) {
		return nil, false, nil
	} else if err != nil {
		return nil, false, err
	}
	return rctx, true, err
}

// SecuritySource is provider of security values (tokens, passwords, etc.).
type SecuritySource interface {
	// CoordinatorApiKey provides CoordinatorApiKey security value.
	// Secret key used only for backend -> coordinator communication.
	CoordinatorApiKey(ctx context.Context, operationName OperationName) (CoordinatorApiKey, error)
}

func (s *Client) securityCoordinatorApiKey(ctx context.Context, operationName OperationName, req *http.Request) error {
	t, err := s.sec.CoordinatorApiKey(ctx, operationName)
	if err != nil {
		return errors.Wrap(err, "security source \"CoordinatorApiKey\"")
	}
	req.Header.Set("Authorization", t.APIKey)
	return nil
}
