openapi: 3.0.0

info:
  version: 0.0.1
  title: GPU Share API
  description: Allows for managing users and devices

paths:
  /health:
    $ref: "./paths/health.yaml"
  /api/devices:
    $ref: "./paths/api/devices/devices.yaml"
  /api/devices/{deviceId}/status:
    $ref: "./paths/api/devices/status.yaml"
  /api/orders:
    $ref: "./paths/api/orders/orders.yaml"
  /api/orders/{orderId}:
    $ref: "./paths/api/orders/id.yaml"
  /api/reviews/device/{deviceId}:
    $ref: "./paths/api/reviews/device.yaml"
  /api/reviews/reviewOrder/{orderId}:
    $ref: "./paths/api/reviews/reviewOrder.yaml"
  /api/reviews/user/{username}:
    $ref: "./paths/api/reviews/user.yaml"
  /api/reviews/userRating/{username}:
    $ref: "./paths/api/reviews/userRating.yaml"
  /api/users/changePassword:
    $ref: "./paths/api/users/changePassword.yaml"
  /api/users/login:
    $ref: "./paths/api/users/login.yaml"
  /api/users/refresh:
    $ref: "./paths/api/users/refresh.yaml"
  /api/users/register:
    $ref: "./paths/api/users/register.yaml"
  /api/wallet:
    $ref: "./paths/api/wallet/wallet.yaml"
  /api/wallet/payoutAccount:
    $ref: "./paths/api/wallet/payoutAccount.yaml"
  /api/wallet/transfer:
    $ref: "./paths/api/wallet/transfer.yaml"

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
