openapi: 3.0.0

info:
  version: 0.0.1
  title: GPU Share API
  # description: ???

paths:
  /health:
    $ref: "./paths/health.yaml"
  /api/devices/{deviceId}/status:
    $ref: "./paths/deviceStatus.yaml"