openapi: 3.0.0

info:
  version: 0.0.1
  title: GPU Share API
  # description: ???

paths:
  /api/devices/{deviceId}/status:
    $ref: "./paths/deviceStatus.yaml"

components:
  parameters:
    deviceId:
      $ref: "./parameters/path/deviceId.yaml"
  schemas:
    DeviceStatus:
      $ref: "./schemas/DeviceStatus.yaml"
  # responses:
  #   someResponse:
  #     $ref: "..."